apiVersion: gcp.kubed.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-app
spec:
  display_name: Example App
  description: Service account for example-app
  roles:
  - roles/storage.objectAdmin
  - roles/secretmanager.secretAccessor
  writeSecretTo:
    namespace: default
    name: example-app-gcp-creds
