apiVersion: gcp.kubed.io/v1alpha1
kind: IdentityPoolProvider
metadata:
  name: github
spec:
  poolId: example-pool
  display_name: GitHub Actions
  description: GitHub Actions OIDC provider for the example org
  attributeCondition: assertion.repository_owner_id == '123456789'
  attributeMapping:
    google.subject: assertion.sub
    attribute.actor: assertion.actor
    attribute.repository: assertion.repository
    attribute.repository_owner: assertion.repository_owner
    attribute.repository_owner_id: assertion.repository_owner_id
  members:
  - serviceAccountName: example-app
    condition: attribute.repository_owner_id/123456789
